steps:
  - label: "build-gnu-x86"
    commands:
     - cargo build --release
    retry:
      automatic: false
    agents:
      platform: x86_64.metal
    plugins:
      - docker#v3.0.1:
          image: "fandree/rust-vmm-dev"
          always-pull: true

  - label: "build-gnu-arm"
    commands:
     - cargo build --release
    retry:
      automatic: false
    agents:
      platform: arm.metal
    plugins:
      - docker#v3.0.1:
          image: "fandree/rust-vmm-dev"
          always-pull: true

  - label: "build-musl-x86"
    commands:
     - cargo build --release --target x86_64-unknown-linux-musl
    retry:
      automatic: false
    agents:
      platform: x86_64.metal
    plugins:
      - docker#v3.0.1:
          image: "fandree/rust-vmm-dev"
          always-pull: true

  - label: "build-musl-arm"
    commands:
     - cargo build --release --target aarch64-unknown-linux-musl
    retry:
      automatic: false
    agents:
      platform: arm.metal
    plugins:
      - docker#v3.0.1:
          image: "fandree/rust-vmm-dev"
          always-pull: true

  - label: "style"
    command: cargo fmt --all -- --check
    retry:
      automatic: false
    agents:
      platform: x86_64.metal
    plugins:
      - docker#v3.0.1:
          image: "fandree/rust-vmm-dev"
          always-pull: true

  - label: "unittests-gnu-x86"
    commands:
     - cargo test
    retry:
      automatic: false
    agents:
      platform: x86_64.metal
    plugins:
      - docker#v3.0.1:
          privileged: true
          image: "fandree/rust-vmm-dev"
          always-pull: true

  - label: "unittests-gnu-arm"
    commands:
     - cargo test
    retry:
      automatic: false
    agents:
      platform: arm.metal
    plugins:
      - docker#v3.0.1:
          privileged: true
          image: "fandree/rust-vmm-dev"
          always-pull: true

  - label: "unittests-musl-x86"
    command:
     - cargo test --target x86_64-unknown-linux-musl
    retry:
      automatic: false
    agents:
      platform: x86_64.metal
    plugins:
      - docker#v3.0.1:
          privileged: true
          image: "fandree/rust-vmm-dev"
          always-pull: true

  - label: "unittests-musl-arm"
    command:
     - cargo test --target aarch64-unknown-linux-musl
    retry:
      automatic: false
    agents:
      platform: arm.metal
    plugins:
      - docker#v3.0.1:
          privileged: true
          image: "fandree/rust-vmm-dev"
          always-pull: true

  - label: "clippy-x86"
    commands:
     - cargo clippy --all
    retry:
      automatic: false
    agents:
      platform: x86_64.metal
    plugins:
      - docker#v3.0.1:
          image: "fandree/rust-vmm-dev"
          always-pull: true

  - label: "coverage-x86"
    commands:
      - pytest tests/test_coverage.py
    retry:
      automatic: false
    agents:
      platform: x86_64.metal
    plugins:
      - docker#v3.0.1:
          privileged: true
          image: "fandree/rust-vmm-dev"
          always-pull: true

  - label: "check-warnings-x86"
    commands:
      - RUSTFLAGS="-D warnings" cargo check --all-targets
    retry:
      automatic: false
    agents:
      platform: x86_64.metal
    plugins:
      - docker#v3.0.1:
          privileged: true
          image: "fandree/rust-vmm-dev"
          always-pull: true

  - label: "check-warnings-arm"
    command:
     - RUSTFLAGS="-D warnings" cargo check --all-targets
    retry:
      automatic: false
    agents:
      platform: arm.metal
    plugins:
      - docker#v3.0.1:
          privileged: true
          image: "fandree/rust-vmm-dev"
          always-pull: true