name: Publish kvm-bindings to crates.io

on:
  push:
    tags: ['kvm-bindings-v*']  # Triggers when pushing tags starting with 'kvm-bindings-v'

jobs:
  publish:
    runs-on: ubuntu-latest
    # environment: release  # Optional: for enhanced security
    permissions:
      id-token: write     # Required for OIDC token exchange
    steps:
    - uses: actions/checkout@v4
    - uses: rust-lang/crates-io-auth-action@v1
      id: auth
    - run: |
        cd kvm-bindings
        cargo publish
      env:
        CARGO_REGISTRY_TOKEN: ${{ steps.auth.outputs.token }}
